#!/system/bin/sh

CORE=`grep -c processor < /proc/cpuinfo` || CORE=2

# Wait until we see some android processes to consider boot is more or less complete
while ! pgrep com.android
do
    sleep 1
done

# Another waiting time for stability
sleep 30

### File System Trim ###
fstrim -v /cache
fstrim -v /data
sync

### I/O ###
for dev in /sys/block/*/queue
do
    echo 0   > ${dev}/add_random
    echo 256 > ${dev}/nr_requests
    echo 512 > ${dev}/read_ahead_kb
    echo "sioplus" > ${dev}/scheduler
done

### Modules ###
for module in /system/lib/modules/*.ko
do
    insmod $module
done

### Net ###
echo "westwood" > /proc/sys/net/ipv4/tcp_congestion_control
# suitable configuration to help reduce network latency
#echo 2 > /proc/sys/net/ipv4/tcp_ecn
#echo 1 > /proc/sys/net/ipv4/tcp_sack
#echo 1 > /proc/sys/net/ipv4/tcp_dsack
#echo 1 > /proc/sys/net/ipv4/tcp_low_latency
#echo 1 > /proc/sys/net/ipv4/tcp_timestamps
# reduce txqueuelen to 0 to switch from a packet queue to a byte one
#for i in /sys/class/net/*
#do
#    echo 0 > ${i}/tx_queue_len
#done

## Random ##
echo 128 > /proc/sys/kernel/random/read_wakeup_threshold
echo 256 > /proc/sys/kernel/random/write_wakeup_threshold

## Misc ##
# disable ASLR
#echo 0 > /proc/sys/kernel/randomize_va_space

# initialize timer slack
#echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns

# decrease fs lease time
#echo 10 > /proc/sys/fs/lease-break-time

### SELinux ###
#setenforce 0

### VM ###
echo 1 > /proc/sys/vm/laptop_mode
# double the default minfree kb
#tmp=`cat /proc/sys/vm/min_free_kbytes`
#mfk=`expr $tmp \* 2`
#echo $mfk > /proc/sys/vm/min_free_kbytes

### Zram ###
sync
i=`echo /sys/block/zram* | wc -w`
zram=`expr $i - 1`
if [ $zram -gt 0 ]; then
    for id in `seq 0 $zram`
    do
	swapoff	/dev/block/zram${id}
	echo 1       > /sys/block/zram${id}/reset
	echo "lz4"   > /sys/block/zram${id}/comp_algorithm
	echo "256M"  > /sys/block/zram${id}/disksize
	echo "$CORE" > /sys/block/zram${id}/max_comp_streams
	mkswap	/dev/block/zram${id}
	swapon	/dev/block/zram${id}
	sync
    done
fi
